#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3DSearch
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SWPlusDB")]
	public partial class SQLRepositoryDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKindaRepository(KindaRepository instance);
    partial void UpdateKindaRepository(KindaRepository instance);
    partial void DeleteKindaRepository(KindaRepository instance);
    #endregion
		
		public SQLRepositoryDataContext() : 
				base(global::_3DSearch.Properties.Settings.Default.SQLConnection1, mappingSource)
		{
			OnCreated();
		}
		
		public SQLRepositoryDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQLRepositoryDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQLRepositoryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQLRepositoryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<KindaRepository> KindaRepositories
		{
			get
			{
				return this.GetTable<KindaRepository>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KindaRepository")]
	public partial class KindaRepository : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private decimal _Size1;
		
		private decimal _Size2;
		
		private decimal _Size3;
		
		private System.Data.Linq.Binary _Model;
		
		private string _Path;
		
		private decimal _DimVal1;
		
		private decimal _DimVal2;
		
		private decimal _DimVal3;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSize1Changing(decimal value);
    partial void OnSize1Changed();
    partial void OnSize2Changing(decimal value);
    partial void OnSize2Changed();
    partial void OnSize3Changing(decimal value);
    partial void OnSize3Changed();
    partial void OnModelChanging(System.Data.Linq.Binary value);
    partial void OnModelChanged();
    partial void OnPathChanging(string value);
    partial void OnPathChanged();
    partial void OnDimVal1Changing(decimal value);
    partial void OnDimVal1Changed();
    partial void OnDimVal2Changing(decimal value);
    partial void OnDimVal2Changed();
    partial void OnDimVal3Changing(decimal value);
    partial void OnDimVal3Changed();
    #endregion
		
		public KindaRepository()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size1", DbType="Decimal(18,0) NOT NULL")]
		public decimal Size1
		{
			get
			{
				return this._Size1;
			}
			set
			{
				if ((this._Size1 != value))
				{
					this.OnSize1Changing(value);
					this.SendPropertyChanging();
					this._Size1 = value;
					this.SendPropertyChanged("Size1");
					this.OnSize1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size2", DbType="Decimal(18,0) NOT NULL")]
		public decimal Size2
		{
			get
			{
				return this._Size2;
			}
			set
			{
				if ((this._Size2 != value))
				{
					this.OnSize2Changing(value);
					this.SendPropertyChanging();
					this._Size2 = value;
					this.SendPropertyChanged("Size2");
					this.OnSize2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size3", DbType="Decimal(18,0) NOT NULL")]
		public decimal Size3
		{
			get
			{
				return this._Size3;
			}
			set
			{
				if ((this._Size3 != value))
				{
					this.OnSize3Changing(value);
					this.SendPropertyChanging();
					this._Size3 = value;
					this.SendPropertyChanged("Size3");
					this.OnSize3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="Image NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this.OnModelChanging(value);
					this.SendPropertyChanging();
					this._Model = value;
					this.SendPropertyChanged("Model");
					this.OnModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Path", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Path
		{
			get
			{
				return this._Path;
			}
			set
			{
				if ((this._Path != value))
				{
					this.OnPathChanging(value);
					this.SendPropertyChanging();
					this._Path = value;
					this.SendPropertyChanged("Path");
					this.OnPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DimVal1", DbType="Decimal(18,0) NOT NULL")]
		public decimal DimVal1
		{
			get
			{
				return this._DimVal1;
			}
			set
			{
				if ((this._DimVal1 != value))
				{
					this.OnDimVal1Changing(value);
					this.SendPropertyChanging();
					this._DimVal1 = value;
					this.SendPropertyChanged("DimVal1");
					this.OnDimVal1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DimVal2", DbType="Decimal(18,0) NOT NULL")]
		public decimal DimVal2
		{
			get
			{
				return this._DimVal2;
			}
			set
			{
				if ((this._DimVal2 != value))
				{
					this.OnDimVal2Changing(value);
					this.SendPropertyChanging();
					this._DimVal2 = value;
					this.SendPropertyChanged("DimVal2");
					this.OnDimVal2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DimVal3", DbType="Decimal(18,0) NOT NULL")]
		public decimal DimVal3
		{
			get
			{
				return this._DimVal3;
			}
			set
			{
				if ((this._DimVal3 != value))
				{
					this.OnDimVal3Changing(value);
					this.SendPropertyChanging();
					this._DimVal3 = value;
					this.SendPropertyChanged("DimVal3");
					this.OnDimVal3Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
